### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by ScarletxZ** [ForumotionJS/jsdic#2]
How about we add some example? Something like {title: "Title here", desc: "Desc here", ex: "Some example" }.

**Comment by Hitsuko** [comment]
That's of course is a great idea to do. I'll make sure to add a draft for it in the next version.

**Comment by Hitsuko** [comment]
This semi-huge update will be updated later, maybe Sunday or Monday, mostly Monday because in Sunday I can't act as a netizen for a long time neither because, yeah, middle-semester exam.
